USE HealthcareHub;
GO

CREATE TABLE raw.MedicareMonthlyEnrollment
(
    MedicareMonthlyEnrollmentRawId BIGINT IDENTITY(1,1) NOT NULL
        CONSTRAINT PK_MedicareMonthlyEnrollment PRIMARY KEY,

    PipelineRunId BIGINT NULL,

    [YEAR] SMALLINT NOT NULL,
    [MONTH] NVARCHAR(20) NOT NULL,

    BENE_GEO_LVL NVARCHAR(20) NULL,
    BENE_STATE_ABRVTN NVARCHAR(10) NULL,
    BENE_STATE_DESC NVARCHAR(100) NULL,
    BENE_COUNTY_DESC NVARCHAR(150) NULL,
    BENE_FIPS_CD NVARCHAR(10) NULL,

    TOT_BENES NVARCHAR(30) NULL,
    ORGNL_MDCR_BENES NVARCHAR(30) NULL,
    MA_AND_OTH_BENES NVARCHAR(30) NULL,

    AGED_TOT_BENES NVARCHAR(30) NULL,
    AGED_ESRD_BENES NVARCHAR(30) NULL,
    AGED_NO_ESRD_BENES NVARCHAR(30) NULL,

    DSBLD_TOT_BENES NVARCHAR(30) NULL,
    DSBLD_ESRD_AND_ESRD_ONLY_BENES NVARCHAR(30) NULL,
    DSBLD_NO_ESRD_BENES NVARCHAR(30) NULL,

    MALE_TOT_BENES NVARCHAR(30) NULL,
    FEMALE_TOT_BENES NVARCHAR(30) NULL,

    WHITE_TOT_BENES NVARCHAR(30) NULL,
    BLACK_TOT_BENES NVARCHAR(30) NULL,
    API_TOT_BENES NVARCHAR(30) NULL,
    HSPNC_TOT_BENES NVARCHAR(30) NULL,
    NATIND_TOT_BENES NVARCHAR(30) NULL,
    OTHR_TOT_BENES NVARCHAR(30) NULL,

    AGE_LT_25_BENES NVARCHAR(30) NULL,
    AGE_25_TO_44_BENES NVARCHAR(30) NULL,
    AGE_45_TO_64_BENES NVARCHAR(30) NULL,
    AGE_65_TO_69_BENES NVARCHAR(30) NULL,
    AGE_70_TO_74_BENES NVARCHAR(30) NULL,
    AGE_75_TO_79_BENES NVARCHAR(30) NULL,
    AGE_80_TO_84_BENES NVARCHAR(30) NULL,
    AGE_85_TO_89_BENES NVARCHAR(30) NULL,
    AGE_90_TO_94_BENES NVARCHAR(30) NULL,
    AGE_GT_94_BENES NVARCHAR(30) NULL,

    DUAL_TOT_BENES NVARCHAR(30) NULL,
    FULL_DUAL_TOT_BENES NVARCHAR(30) NULL,
    PART_DUAL_TOT_BENES NVARCHAR(30) NULL,
    NODUAL_TOT_BENES NVARCHAR(30) NULL,

    QMB_ONLY_BENES NVARCHAR(30) NULL,
    QMB_PLUS_BENES NVARCHAR(30) NULL,
    SLMB_ONLY_BENES NVARCHAR(30) NULL,
    SLMB_PLUS_BENES NVARCHAR(30) NULL,
    QDWI_QI_BENES NVARCHAR(30) NULL,
    OTHR_FULL_DUAL_MDCD_BENES NVARCHAR(30) NULL,

    A_B_TOT_BENES NVARCHAR(30) NULL,
    A_B_ORGNL_MDCR_BENES NVARCHAR(30) NULL,
    A_B_MA_AND_OTH_BENES NVARCHAR(30) NULL,

    A_TOT_BENES NVARCHAR(30) NULL,
    A_ORGNL_MDCR_BENES NVARCHAR(30) NULL,
    A_MA_AND_OTH_BENES NVARCHAR(30) NULL,

    B_TOT_BENES NVARCHAR(30) NULL,
    B_ORGNL_MDCR_BENES NVARCHAR(30) NULL,
    B_MA_AND_OTH_BENES NVARCHAR(30) NULL,

    PRSCRPTN_DRUG_TOT_BENES NVARCHAR(30) NULL,
    PRSCRPTN_DRUG_PDP_BENES NVARCHAR(30) NULL,
    PRSCRPTN_DRUG_MAPD_BENES NVARCHAR(30) NULL,
    PRSCRPTN_DRUG_DEEMED_ELIGIBLE_FULL_LIS_BENES NVARCHAR(30) NULL,
    PRSCRPTN_DRUG_FULL_LIS_BENES NVARCHAR(30) NULL,
    PRSCRPTN_DRUG_PARTIAL_LIS_BENES NVARCHAR(30) NULL,
    PRSCRPTN_DRUG_NO_LIS_BENES NVARCHAR(30) NULL,

    SourceFileName NVARCHAR(260) NULL,
    LoadedUtc DATETIME2(0) NOT NULL
        CONSTRAINT DF_MedicareMonthlyEnrollment_LoadedUtc
        DEFAULT SYSUTCDATETIME(),

    CONSTRAINT FK_MedicareMonthlyEnrollment_PipelineRun
        FOREIGN KEY (PipelineRunId)
        REFERENCES ops.PipelineRun(PipelineRunId)
);
GO