USE HealthcareHub;
GO

CREATE TABLE stage.MedicareMonthlyEnrollment
(
    MedicareMonthlyEnrollmentStageId BIGINT IDENTITY(1,1) NOT NULL
        CONSTRAINT PK_Stage_MedicareMonthlyEnrollment PRIMARY KEY,

    MedicareMonthlyEnrollmentRawId BIGINT NOT NULL,
    PipelineRunId BIGINT NOT NULL,

    ReportingYear SMALLINT NOT NULL,
    ReportingMonth TINYINT NULL,
    ReportingPeriodStart DATE NULL,
    IsAnnualSummary BIT NOT NULL,

    GeographyLevel NVARCHAR(20) NULL,
    StateAbbreviation NVARCHAR(10) NULL,
    StateName NVARCHAR(100) NULL,
    CountyName NVARCHAR(150) NULL,
    GeographyFips NVARCHAR(5) NULL,

    TOT_BENES BIGINT NULL,
    ORGNL_MDCR_BENES BIGINT NULL,
    MA_AND_OTH_BENES BIGINT NULL,

    AGED_TOT_BENES BIGINT NULL,
    AGED_ESRD_BENES BIGINT NULL,
    AGED_NO_ESRD_BENES BIGINT NULL,

    DSBLD_TOT_BENES BIGINT NULL,
    DSBLD_ESRD_AND_ESRD_ONLY_BENES BIGINT NULL,
    DSBLD_NO_ESRD_BENES BIGINT NULL,

    MALE_TOT_BENES BIGINT NULL,
    FEMALE_TOT_BENES BIGINT NULL,

    WHITE_TOT_BENES BIGINT NULL,
    BLACK_TOT_BENES BIGINT NULL,
    API_TOT_BENES BIGINT NULL,
    HSPNC_TOT_BENES BIGINT NULL,
    NATIND_TOT_BENES BIGINT NULL,
    OTHR_TOT_BENES BIGINT NULL,

    AGE_LT_25_BENES BIGINT NULL,
    AGE_25_TO_44_BENES BIGINT NULL,
    AGE_45_TO_64_BENES BIGINT NULL,
    AGE_65_TO_69_BENES BIGINT NULL,
    AGE_70_TO_74_BENES BIGINT NULL,
    AGE_75_TO_79_BENES BIGINT NULL,
    AGE_80_TO_84_BENES BIGINT NULL,
    AGE_85_TO_89_BENES BIGINT NULL,
    AGE_90_TO_94_BENES BIGINT NULL,
    AGE_GT_94_BENES BIGINT NULL,

    DUAL_TOT_BENES BIGINT NULL,
    FULL_DUAL_TOT_BENES BIGINT NULL,
    PART_DUAL_TOT_BENES BIGINT NULL,
    NODUAL_TOT_BENES BIGINT NULL,

    QMB_ONLY_BENES BIGINT NULL,
    QMB_PLUS_BENES BIGINT NULL,
    SLMB_ONLY_BENES BIGINT NULL,
    SLMB_PLUS_BENES BIGINT NULL,
    QDWI_QI_BENES BIGINT NULL,
    OTHR_FULL_DUAL_MDCD_BENES BIGINT NULL,

    A_B_TOT_BENES BIGINT NULL,
    A_B_ORGNL_MDCR_BENES BIGINT NULL,
    A_B_MA_AND_OTH_BENES BIGINT NULL,

    A_TOT_BENES BIGINT NULL,
    A_ORGNL_MDCR_BENES BIGINT NULL,
    A_MA_AND_OTH_BENES BIGINT NULL,

    B_TOT_BENES BIGINT NULL,
    B_ORGNL_MDCR_BENES BIGINT NULL,
    B_MA_AND_OTH_BENES BIGINT NULL,

    PRSCRPTN_DRUG_TOT_BENES BIGINT NULL,
    PRSCRPTN_DRUG_PDP_BENES BIGINT NULL,
    PRSCRPTN_DRUG_MAPD_BENES BIGINT NULL,
    PRSCRPTN_DRUG_DEEMED_ELIGIBLE_FULL_LIS_BENES BIGINT NULL,
    PRSCRPTN_DRUG_FULL_LIS_BENES BIGINT NULL,
    PRSCRPTN_DRUG_PARTIAL_LIS_BENES BIGINT NULL,
    PRSCRPTN_DRUG_NO_LIS_BENES BIGINT NULL,

    IsAnyValueSuppressed BIT NOT NULL,
    SuppressedValueCount SMALLINT NOT NULL,

    SourceFileName NVARCHAR(260) NULL,

    StagedUtc DATETIME2(0) NOT NULL
        CONSTRAINT DF_Stage_MedicareMonthlyEnrollment_StagedUtc
        DEFAULT SYSUTCDATETIME(),

    CONSTRAINT UQ_Stage_MedicareMonthlyEnrollment_RawId
        UNIQUE (MedicareMonthlyEnrollmentRawId),

    CONSTRAINT FK_Stage_MedicareMonthlyEnrollment_Raw
        FOREIGN KEY (MedicareMonthlyEnrollmentRawId)
        REFERENCES raw.MedicareMonthlyEnrollment(MedicareMonthlyEnrollmentRawId),

    CONSTRAINT FK_Stage_MedicareMonthlyEnrollment_PipelineRun
        FOREIGN KEY (PipelineRunId)
        REFERENCES ops.PipelineRun(PipelineRunId)
);
GO